version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    target-branch: "main"
    assignees:
      - "fasashen"
      - "memekas"
      - "askolesov"
      - "Balevka"
    commit-message:
      prefix: "deps"
    # Group minor/patch updates into a single PR
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    target-branch: "main"
    assignees:
      - "fasashen"
      - "memekas"
      - "askolesov"
      - "Balevka"
    commit-message:
      prefix: "deps"
    # Group minor/patch updates into a single PR
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    target-branch: "main"
    assignees:
      - "fasashen"
      - "memekas"
      - "askolesov"
      - "Balevka"
    commit-message:
      prefix: "deps"
    # Group minor/patch updates into a single PR
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
